"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class grSim_RobotReplacement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    DIR_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    YELLOWTEAM_FIELD_NUMBER: builtins.int
    TURNON_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    dir: builtins.float
    id: builtins.int
    yellowteam: builtins.bool
    turnon: builtins.bool

    def __init__(self, *, x: builtins.float | None=..., y: builtins.float | None=..., dir: builtins.float | None=..., id: builtins.int | None=..., yellowteam: builtins.bool | None=..., turnon: builtins.bool | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['dir', b'dir', 'id', b'id', 'turnon', b'turnon', 'x', b'x', 'y', b'y', 'yellowteam', b'yellowteam']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['dir', b'dir', 'id', b'id', 'turnon', b'turnon', 'x', b'x', 'y', b'y', 'yellowteam', b'yellowteam']) -> None:
        ...
global___grSim_RobotReplacement = grSim_RobotReplacement

@typing.final
class grSim_BallReplacement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    VX_FIELD_NUMBER: builtins.int
    VY_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    vx: builtins.float
    vy: builtins.float

    def __init__(self, *, x: builtins.float | None=..., y: builtins.float | None=..., vx: builtins.float | None=..., vy: builtins.float | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['vx', b'vx', 'vy', b'vy', 'x', b'x', 'y', b'y']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['vx', b'vx', 'vy', b'vy', 'x', b'x', 'y', b'y']) -> None:
        ...
global___grSim_BallReplacement = grSim_BallReplacement

@typing.final
class grSim_Replacement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BALL_FIELD_NUMBER: builtins.int
    ROBOTS_FIELD_NUMBER: builtins.int

    @property
    def ball(self) -> global___grSim_BallReplacement:
        ...

    @property
    def robots(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___grSim_RobotReplacement]:
        ...

    def __init__(self, *, ball: global___grSim_BallReplacement | None=..., robots: collections.abc.Iterable[global___grSim_RobotReplacement] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['ball', b'ball']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['ball', b'ball', 'robots', b'robots']) -> None:
        ...
global___grSim_Replacement = grSim_Replacement