"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
from .. import grsim
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class grSim_Packet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMANDS_FIELD_NUMBER: builtins.int
    REPLACEMENT_FIELD_NUMBER: builtins.int

    @property
    def commands(self) -> grsim.grSim_Commands_pb2.grSim_Commands:
        ...

    @property
    def replacement(self) -> grsim.grSim_Replacement_pb2.grSim_Replacement:
        ...

    def __init__(self, *, commands: grsim.grSim_Commands_pb2.grSim_Commands | None=..., replacement: grsim.grSim_Replacement_pb2.grSim_Replacement | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['commands', b'commands', 'replacement', b'replacement']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['commands', b'commands', 'replacement', b'replacement']) -> None:
        ...
global___grSim_Packet = grSim_Packet