"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class grSim_Robot_Command(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    KICKSPEEDX_FIELD_NUMBER: builtins.int
    KICKSPEEDZ_FIELD_NUMBER: builtins.int
    VELTANGENT_FIELD_NUMBER: builtins.int
    VELNORMAL_FIELD_NUMBER: builtins.int
    VELANGULAR_FIELD_NUMBER: builtins.int
    SPINNER_FIELD_NUMBER: builtins.int
    WHEELSSPEED_FIELD_NUMBER: builtins.int
    WHEEL1_FIELD_NUMBER: builtins.int
    WHEEL2_FIELD_NUMBER: builtins.int
    WHEEL3_FIELD_NUMBER: builtins.int
    WHEEL4_FIELD_NUMBER: builtins.int
    id: builtins.int
    kickspeedx: builtins.float
    kickspeedz: builtins.float
    veltangent: builtins.float
    velnormal: builtins.float
    velangular: builtins.float
    spinner: builtins.bool
    wheelsspeed: builtins.bool
    wheel1: builtins.float
    wheel2: builtins.float
    wheel3: builtins.float
    wheel4: builtins.float

    def __init__(self, *, id: builtins.int | None=..., kickspeedx: builtins.float | None=..., kickspeedz: builtins.float | None=..., veltangent: builtins.float | None=..., velnormal: builtins.float | None=..., velangular: builtins.float | None=..., spinner: builtins.bool | None=..., wheelsspeed: builtins.bool | None=..., wheel1: builtins.float | None=..., wheel2: builtins.float | None=..., wheel3: builtins.float | None=..., wheel4: builtins.float | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'kickspeedx', b'kickspeedx', 'kickspeedz', b'kickspeedz', 'spinner', b'spinner', 'velangular', b'velangular', 'velnormal', b'velnormal', 'veltangent', b'veltangent', 'wheel1', b'wheel1', 'wheel2', b'wheel2', 'wheel3', b'wheel3', 'wheel4', b'wheel4', 'wheelsspeed', b'wheelsspeed']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'kickspeedx', b'kickspeedx', 'kickspeedz', b'kickspeedz', 'spinner', b'spinner', 'velangular', b'velangular', 'velnormal', b'velnormal', 'veltangent', b'veltangent', 'wheel1', b'wheel1', 'wheel2', b'wheel2', 'wheel3', b'wheel3', 'wheel4', b'wheel4', 'wheelsspeed', b'wheelsspeed']) -> None:
        ...
global___grSim_Robot_Command = grSim_Robot_Command

@typing.final
class grSim_Commands(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIMESTAMP_FIELD_NUMBER: builtins.int
    ISTEAMYELLOW_FIELD_NUMBER: builtins.int
    ROBOT_COMMANDS_FIELD_NUMBER: builtins.int
    timestamp: builtins.float
    isteamyellow: builtins.bool

    @property
    def robot_commands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___grSim_Robot_Command]:
        ...

    def __init__(self, *, timestamp: builtins.float | None=..., isteamyellow: builtins.bool | None=..., robot_commands: collections.abc.Iterable[global___grSim_Robot_Command] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['isteamyellow', b'isteamyellow', 'timestamp', b'timestamp']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['isteamyellow', b'isteamyellow', 'robot_commands', b'robot_commands', 'timestamp', b'timestamp']) -> None:
        ...
global___grSim_Commands = grSim_Commands