"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
from .. import engine
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
from .. import state
from .. import statemachine
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Output(google.protobuf.message.Message):
    """Message format that is pushed from the GC to the client"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MATCH_STATE_FIELD_NUMBER: builtins.int
    GC_STATE_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int

    @property
    def match_state(self) -> state.ssl_gc_state_pb2.State:
        """The current match state"""

    @property
    def gc_state(self) -> engine.ssl_gc_engine_pb2.GcState:
        """The current GC state"""

    @property
    def protocol(self) -> global___Protocol:
        """The protocol"""

    @property
    def config(self) -> engine.ssl_gc_engine_config_pb2.Config:
        """The engine config"""

    def __init__(self, *, match_state: state.ssl_gc_state_pb2.State | None=..., gc_state: engine.ssl_gc_engine_pb2.GcState | None=..., protocol: global___Protocol | None=..., config: engine.ssl_gc_engine_config_pb2.Config | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['config', b'config', 'gc_state', b'gc_state', 'match_state', b'match_state', 'protocol', b'protocol']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['config', b'config', 'gc_state', b'gc_state', 'match_state', b'match_state', 'protocol', b'protocol']) -> None:
        ...
global___Output = Output

@typing.final
class Protocol(google.protobuf.message.Message):
    """The game protocol"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DELTA_FIELD_NUMBER: builtins.int
    ENTRY_FIELD_NUMBER: builtins.int
    delta: builtins.bool
    "Is this a delta only?\n    Entries that were already sent are not sent again, because the protocol is immutable anyway.\n    But if the game is reset, the whole protocol must be replaced. That's what this flag is for.\n    "

    @property
    def entry(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProtocolEntry]:
        """The (delta) list of entries"""

    def __init__(self, *, delta: builtins.bool | None=..., entry: collections.abc.Iterable[global___ProtocolEntry] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['delta', b'delta']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['delta', b'delta', 'entry', b'entry']) -> None:
        ...
global___Protocol = Protocol

@typing.final
class ProtocolEntry(google.protobuf.message.Message):
    """A protocol entry of a change"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    CHANGE_FIELD_NUMBER: builtins.int
    MATCH_TIME_ELAPSED_FIELD_NUMBER: builtins.int
    STAGE_TIME_ELAPSED_FIELD_NUMBER: builtins.int
    id: builtins.int
    'Id of the entry'

    @property
    def change(self) -> statemachine.ssl_gc_change_pb2.Change:
        """The change that was made"""

    @property
    def match_time_elapsed(self) -> google.protobuf.duration_pb2.Duration:
        """The match time elapsed when this change was made"""

    @property
    def stage_time_elapsed(self) -> google.protobuf.duration_pb2.Duration:
        """The stage time elapsed when this change was made"""

    def __init__(self, *, id: builtins.int | None=..., change: statemachine.ssl_gc_change_pb2.Change | None=..., match_time_elapsed: google.protobuf.duration_pb2.Duration | None=..., stage_time_elapsed: google.protobuf.duration_pb2.Duration | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['change', b'change', 'id', b'id', 'match_time_elapsed', b'match_time_elapsed', 'stage_time_elapsed', b'stage_time_elapsed']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['change', b'change', 'id', b'id', 'match_time_elapsed', b'match_time_elapsed', 'stage_time_elapsed', b'stage_time_elapsed']) -> None:
        ...
global___ProtocolEntry = ProtocolEntry

@typing.final
class Input(google.protobuf.message.Message):
    """Message format that can be send from the client to the GC"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHANGE_FIELD_NUMBER: builtins.int
    RESET_MATCH_FIELD_NUMBER: builtins.int
    CONFIG_DELTA_FIELD_NUMBER: builtins.int
    CONTINUE_ACTION_FIELD_NUMBER: builtins.int
    reset_match: builtins.bool
    'Reset the match'

    @property
    def change(self) -> statemachine.ssl_gc_change_pb2.Change:
        """A change to be enqueued into the GC engine"""

    @property
    def config_delta(self) -> engine.ssl_gc_engine_config_pb2.Config:
        """An updated config delta"""

    @property
    def continue_action(self) -> engine.ssl_gc_engine_pb2.ContinueAction:
        """Continue with action"""

    def __init__(self, *, change: statemachine.ssl_gc_change_pb2.Change | None=..., reset_match: builtins.bool | None=..., config_delta: engine.ssl_gc_engine_config_pb2.Config | None=..., continue_action: engine.ssl_gc_engine_pb2.ContinueAction | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['change', b'change', 'config_delta', b'config_delta', 'continue_action', b'continue_action', 'reset_match', b'reset_match']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['change', b'change', 'config_delta', b'config_delta', 'continue_action', b'continue_action', 'reset_match', b'reset_match']) -> None:
        ...
global___Input = Input